# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSOvzmnWwAG6hOstTfit0AmBjgVTPs1x
"""

def helper():
    print("This is a helper function!")
    
